[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/me"
  to = "/.netlify/functions/me"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/upload-url"
  to = "/.netlify/functions/upload-url"
  status = 200

[[redirects]]
  from = "/api/send"
  to = "/.netlify/functions/send"
  status = 200

[[redirects]]
  from = "/api/inbox"
  to = "/.netlify/functions/inbox"
  status = 200

[[redirects]]
  from = "/api/sent"
  to = "/.netlify/functions/sent"
  status = 200

[[redirects]]
  from = "/api/download-url"
  to = "/.netlify/functions/download-url"
  status = 200

[[redirects]]
  from = "/api/delete"
  to = "/.netlify/functions/delete"
  status = 200
